name: build aio-mariadb

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile.mariadb
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            tdim/aio-server:mariadb
            tdim/aio-server:mariadb-2.0.0
            ghcr.io/hima-pro/aio-server:mariadb
            ghcr.io/hima-pro/aio-server:mariadb-2.0.0